# Original Authors: Navneet Potti, Nabarun Nag and Jignesh Patel
require 'yaml'

# IP Address for the private VM network
ip_address = "192.168.10.200"

# Basic Vagrant config (API version 2)
Vagrant.configure(2) do |config|

  # Base box: Centos-7 box
  # NOTE: Over time the VMI below may become outdated, so may need to be
  #       substituted with a more recent VMI
  config.vm.box = "centos/7"
# config.vm.box = "box-cutter/centos72"

  # Make this VM reachable on the host network as well, so that other
  # VM's running other browsers can access our dev server.
  config.vm.network :private_network, ip: ip_address

  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true

  # Give a reasonable amount of cpu and memory to the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "libgopherwood-dev-host" # Name in VirtualBox
    vb.memory = 8192
    vb.cpus = 4
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", "1000"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-start"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore", "1"]
  end

  # Make the GPDB code folder will be visible as /gpdb in the virtual machine
  config.vm.synced_folder "../.", "/gopherwood", owner: 555, group: 555

  if File.file?('vagrant-local.yml')
    local_config = YAML::load_file('vagrant-local.yml')
    local_config['synced_folder'].each do |folder|
      config.vm.synced_folder folder['local'], folder['shared'] unless folder['local'].nil? or folder['shared'].nil?
    end
  end

  # config ssh
  config.vm.provision "ssh", type: "shell", path: "vagrant-ssh.sh"

  # Install packages that are needed to build and run GPDB
  config.vm.provision "shell", path: "vagrant-setup.sh"

  default_name = "default"
  # use the trick to change user hashdata after "vagrant up"
  if File.file?('.vagrant/machines/' + default_name + '/virtualbox/id')
    config.ssh.username = "hashdata"
    config.ssh.private_key_path = "./id_rsa"
  end

end
